version: '2'
services:
    db:
        image: postgres:9.5
        restart: always
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data:/var/lib/postgresql/data
    odoo:
        # build:
        #     context: ./data
        #     dockerfile: Dockerfile-dev-$ODOO_VERSION
        # TODO ver como hacemos par que esto se cambie desde otro lugar
        image: $ODOO_IMAGE:$ODOO_VERSION
        restart: always
        external_links:
            - aeroo:aeroo
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "8072:8072"
            - "3500:3500"
            - "6479:6479"
            - "5678:5678"
        volumes:
            - ./data/custom-addons:/opt/odoo/custom-addons
            - ./data/odoo/backups:/var/odoo/backups/
            - ./data/odoo/backups/syncked:/var/odoo/backups/syncked
            - odoo_data:/opt/odoo/data
        env_file:
            - .env
        #these extra env items are for nginx-proxy automated reverse proxy
        #we need to design an automated hostname/dns subsystem 
        environment:
            - VIRTUAL_HOST=odoo0.local
            - VIRTUAL_PORT=8069



#dependency: nginx-proxy must be running before and must create this network
#networks:
#  default:
#    external:
#      name: dockernginxadhoc_backend

volumes:
    pg_data:
    odoo_data:
